#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=42 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=8 \
    padding_right=8 \
    notch_width=230 \
    display=main

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:12.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify e \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    icon.font="$FONT_FACE:Bold:20.0" \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    icon.color=0xff24273a \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item weather.moon q \
    --set weather.moon \
    background.color=0x667dc4e4 \
    background.padding_right=-1 \
    icon.color=0xff181926 \
    icon.font="$FONT_FACE:Bold:22.0" \
    icon.padding_left=4 \
    icon.padding_right=3 \
    label.drawing=off \
    --subscribe weather.moon mouse.clicked

sketchybar --add item weather q \
    --set weather \
    icon= \
    icon.color=0xfff5bde6 \
    update_freq=1800 \
    script="$PLUGIN_SHARED_DIR/weather.sh" \
    --subscribe weather system_woke

sketchybar --add item aqi q \
    --set aqi \
    icon= \
    icon.color=0xffcad3f5 \
    label="AQI" \
    update_freq=3600 \
    script="$PLUGIN_SHARED_DIR/aqi.sh" \
    --subscribe aqi system_woke

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar -m --add item ram_percentage right \
              --set ram_percentage \
                    icon="" \
                    icon.color="0xffffffff" \
                    y_offset=0 \
                    update_freq=5 \
                    label.width=32 \
                    label.align=center \
                    script="~/.config/sketchybar/plugins/ram.sh"

sketchybar -m --add item cpu_percent right \
              --set cpu_percent \
                    icon="" \
                    icon.color="0xffffffff" \
                    y_offset=0 \
                    update_freq=5 \
                    label.width=32 \
                    label.align=center \
                    script="~/.config/sketchybar/plugins/cpu.sh"

# CPU Temperature monitoring
sketchybar -m --add item cpu_temp right \
              --set cpu_temp \
                    y_offset=0 \
                    update_freq=5 \
                    script="~/.config/sketchybar/plugins/temperature.sh"

sketchybar --add event aerospace_workspace_change

sketchybar --add item space_creator left \
    --set space_creator drawing=off \
    --subscribe space_creator aerospace_workspace_change \
    --set space_creator script="$PLUGIN_SHARED_DIR/aerospace_list.sh"

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        icon.padding_left=0 \
        icon.padding_right=0 \
        label.padding_left=4 \
        background.drawing=off \
        padding_left=5 \
        label.width=20 \
        label.height=20 \
        label.align="center" \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

sketchybar --add item front_app left \
    --set front_app \
    background.color=0x00000000 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=0 \
    icon.color=0xffcad3f5 \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=0 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:12.0" \
    label.drawing=yes

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.name \
    --subscribe front_app front_app_switched

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
